export enum SriLankaHospitals {
    // Government Hospitals
    NATIONAL_HOSPITAL_COLOMBO = "National Hospital Colombo",
    COLOMBO_NORTH_TEACHING_HOSPITAL = "Colombo North Teaching Hospital (Ragama)",
    COLOMBO_SOUTH_TEACHING_HOSPITAL = "Colombo South Teaching Hospital (Kalubowila)",
    KARAPITIYA_TEACHING_HOSPITAL = "Karapitiya Teaching Hospital (Galle)",
    KANDY_TEACHING_HOSPITAL = "Kandy Teaching Hospital",
    TEACHING_HOSPITAL_JAFFNA = "Teaching Hospital Jaffna",
    GENERAL_HOSPITAL_KURUNEGALA = "General Hospital Kurunegala",
    GENERAL_HOSPITAL_KANDY = "General Hospital Kandy",
    GENERAL_HOSPITAL_GALLE = "General Hospital Galle",
    GENERAL_HOSPITAL_AMPARA = "General Hospital Ampara",
    GENERAL_HOSPITAL_BADULLA = "General Hospital Badulla",
    GENERAL_HOSPITAL_MATARA = "General Hospital Matara",
    GENERAL_HOSPITAL_ANURADHAPURA = "General Hospital Anuradhapura",
    GENERAL_HOSPITAL_BATTICALOA = "General Hospital Batticaloa",
    GENERAL_HOSPITAL_CHILAW = "General Hospital Chilaw",
    GENERAL_HOSPITAL_HAMBANTOTA = "General Hospital Hambantota",
    GENERAL_HOSPITAL_JAFFNA = "General Hospital Jaffna",
    GENERAL_HOSPITAL_KEGALLE = "General Hospital Kegalle",
    GENERAL_HOSPITAL_KILINOCHCHI = "General Hospital Kilinochchi",
    GENERAL_HOSPITAL_MONARAGALA = "General Hospital Monaragala",
    GENERAL_HOSPITAL_MULLAITIVU = "General Hospital Mullaitivu",
    GENERAL_HOSPITAL_POINT_PEDRO = "General Hospital Point Pedro",
    GENERAL_HOSPITAL_PUTTALAM = "General Hospital Puttalam",
    GENERAL_HOSPITAL_RATNAPURA = "General Hospital Ratnapura",
    GENERAL_HOSPITAL_TRINCOMALEE = "General Hospital Trincomalee",
    GENERAL_HOSPITAL_VAVUNIYA = "General Hospital Vavuniya",
    BASE_HOSPITAL_HOMAGAMA = "Base Hospital Homagama",
    BASE_HOSPITAL_KALUBOWILA = "Base Hospital Kalubowila",
    BASE_HOSPITAL_KULIYAPITIYA = "Base Hospital Kuliyapitiya",
    BASE_HOSPITAL_POLONNARUWA = "Base Hospital Polonnaruwa",
    BASE_HOSPITAL_WATHUPITIWALA = "Base Hospital Wathupitiwala",
    
    // Private Hospitals
    ASIRI_CENTRAL_HOSPITAL = "Asiri Central Hospital (Colombo)",
    ASIRI_SURGICAL_HOSPITAL = "Asiri Surgical Hospital (Colombo)",
    NAWALOKA_HOSPITAL = "Nawaloka Hospital (Colombo)",
    LANKA_HOSPITALS = "Lanka Hospitals (Colombo)",
    DURDANS_HOSPITAL = "Durdans Hospital (Colombo)",
    HEMAS_HOSPITAL = "Hemas Hospital (Wattala)",
    HEMAS_SOUTHERN_HOSPITAL = "Hemas Southern Hospital (Galle)",
    NINEWELLS_HOSPITAL = "Ninewells Hospital (Colombo)",
    HEMAS_HOSPITAL_THALAWATHUGODA = "Hemas Hospital Thalawathugoda",
    NAWALOKA_HOSPITALS_WATTALA = "Nawaloka Hospitals Wattala",
    NAWALOKA_MEDICAL_CENTER = "Nawaloka Medical Center (Negombo)",
    
    // Other Hospitals
    CENTRAL_HOSPITAL_KEGALLE = "Central Hospital Kegalle",
    CENTRAL_HOSPITAL_RATNAPURA = "Central Hospital Ratnapura",
    CENTRAL_HOSPITAL_BATTICALOA = "Central Hospital Batticaloa",
    CENTRAL_HOSPITAL_MULLAITIVU = "Central Hospital Mullaitivu",
    CENTRAL_HOSPITAL_POINT_PEDRO = "Central Hospital Point Pedro",
    CENTRAL_HOSPITAL_VAVUNIYA = "Central Hospital Vavuniya",
    CENTRAL_HOSPITAL_WATHUPITIWALA = "Central Hospital Wathupitiwala",
    CENTRAL_HOSPITAL_WELISARA = "Central Hospital Welisara",
    CENTRAL_HOSPITAL_WELLAWATTA = "Central Hospital Wellawatta",
    CENTRAL_HOSPITAL_WELLAWAYA = "Central Hospital Wellawaya",
    CENTRAL_HOSPITAL_WATTALA = "Central Hospital Wattala",

    NO_HOSPITAL = "No Hospital"
}
